import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { DataProvider } from "@/Context/Context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <div className="min-h-dvh mx-auto bg-main-background">
          <Header />

          <main>
            <DataProvider>
              {children}
            </DataProvider>
          </main>

          <Footer />
        </div>

      </body>
    </html>
  );
}
